use_default_settings:
  engines:
    keep_only:
      - bing
      - sogou

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "__XIAOWEI_SEARXNG_SECRET__"
  limiter: false
  public_instance: false
  image_proxy: false

search:
  formats:
    - json

engines:
  - name: bing
    engine: bing
    shortcut: bi
    base_url: https://cn.bing.com
    disabled: false
  - name: sogou
    engine: sogou
    shortcut: sogou
    disabled: false
