import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ acceptDownloads: true });
const page = await ctx.newPage();
page.on('console', (m) => console.log('[console]', m.type(), m.text().slice(0, 220)));
page.on('requestfailed', (r) => console.log('[requestfailed]', r.url(), r.failure()?.errorText));
await page.goto('https://wuguobin123.github.io/', { timeout: 30000 });
const link = page.locator('a.download-link', { hasText: '.EXE' });
console.log('href =', await link.getAttribute('href'));
const downloadPromise = page.waitForEvent('download', { timeout: 8000 }).catch(() => null);
await link.click();
const download = await downloadPromise;
console.log(download ? `下载已触发: ${download.suggestedFilename()}` : '8 秒内无任何下载事件 —— 被浏览器拦截');
await browser.close();
